version: '3.4'

services:
  tasklist:
    image: ${DOCKER_REGISTRY-}tasklist
    build:
      context: .
      dockerfile: TaskList/Dockerfile
    depends_on:
      - sqlserver     

  sqlserver:
    container_name: db_service
    image: mcr.microsoft.com/mssql/server:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "mco#2025"   
    ports:
      - '1433:1433'    
    expose:
      - 1433

